### PR TITLE
[dist][lint] Update to probot@9, jest@24, standard@12; fix lint issue

### LINKED ISSUE #20: dependency on probot is pinned to 7.x.x
package.json has probot dependency as "^7.5.1", whereas the latest probot is 9.0.2
is this intentional, or the plugin will work fine with 9.x.x and dependency just needs to be updated?

### PR DESCRIPTION
**Pull request by decompil3d**
I've built a lambda using this + `probot@9` and all seems to work fine. Tests pass with this update as well.

Let me know if I can change anything to help this move forward. Thanks!

Closes #20

### CODE REVIEW

**Comment by decompil3d** [comment]
@tcbyrd @JasonEtco Hoping to get your review on this. Should be a quick one. Thanks!

**Comment by Mihailoff** [comment]
Please merge

**Comment by decompil3d** [comment]
@Mihailoff All up to date now

**Comment by decompil3d** [comment]
@tcbyrd @JasonEtco Ping -- any chance we can get this merged?

**Comment by decompil3d** [comment]
@JasonEtco Are you going to handle the version bump & publish, or would you like me to open a PR for that?

**Comment by JasonEtco** [comment]
Done 👍 just wanted to get #30 out as well. Published as 0.4.0: https://www.npmjs.com/package/@probot/serverless-lambda/v/0.4.0

**Pull request merged**
