### PR TITLE
fix: correctly handle base64 encoded message body (ApiGateway)

### PR DESCRIPTION
**Pull request by nimrodolev**
This solves #32

### CODE REVIEW

**Comment by JasonEtco** [comment]
I pressed the wrong button 😅

**Comment by nimrodolev** [comment]
Hey, thanks for the quick merge 🙏 
Just out of interest, I see there's no CI setup - when do you usually ship new versions to npm?

**Comment by JasonEtco** [comment]
Sorry about the wait @nimrodolev; [version 0.5.0 is now published](https://www.npmjs.com/package/@probot/serverless-lambda/v/0.5.0)!

**Comment by nimrodolev** [comment]
Thanks for the update, @JasonEtco!
Would you be open for a PR with Travis integration for automatic publishing to NPM?

**Pull request merged**
